language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script: yarn inspect && yarn build
before_deploy: yarn global add now
deploy:
  - provider: script
    script: cd ./dist && now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true